### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dragon2110** [Nyumat/CS162_Repo#2]
@Nyumat In the header file why don't we name our parameters?

**Comment by dragon2110** [comment]
@Nyumat In the make file i see you have a flag what is the difference if you right it in the first line without a flag

**Comment by Nyumat** [comment]
> @Nyumat In the header file why don't we name our parameters?

When the functions are called, the compiler does the work of using the parameters specified in the implementation files.

> @Nyumat In the make file i see you have a flag what is the difference if you right it in the first line without a flag

There is no difference. I just added the flag because I find it simple to read for when I want multiple flags. For this assignment though, I only needed the c++11 compilation flag.
